### ISSUE TITLE
Make UI better

### ISSUE THREAD

**Issue by crystal7-io** [luckieluckie/Calculator#1]
The current UI is seems kinda off, maybe you can make a better UI.

**Comment by crystal7-io** [comment]
Yo, made this in Figma:

![Android Large - 1](https://github.com/luckieluckie/Calculator/assets/150055488/562c536c-3e43-4153-8e88-fcebe1c2d6d2)

**Comment by luckieluckie** [comment]
hmm, it looks so good, i'll try designing it

**Comment by luckieluckie** [comment]
check it , ui changed
